-- M9 Community moderation, reporting, and database-boundary rate limits.

create table if not exists public.content_reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  entry_id uuid references public.content_entries(id) on delete cascade,
  reply_id uuid references public.content_replies(id) on delete cascade,
  reason text not null check (reason in ('spam', 'harassment', 'hate', 'sexual', 'violence', 'misinformation', 'other')),
  details text,
  status text not null default 'pending' check (status in ('pending', 'reviewed', 'dismissed', 'actioned')),
  resolved_by uuid references public.profiles(id) on delete set null,
  resolution_note text,
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  constraint content_reports_one_target check ((entry_id is not null)::integer + (reply_id is not null)::integer = 1),
  constraint content_reports_details_length check (details is null or char_length(details) <= 1000)
);

create unique index if not exists content_reports_pending_entry_uidx
on public.content_reports(reporter_id, entry_id) where entry_id is not null and status = 'pending';
create unique index if not exists content_reports_pending_reply_uidx
on public.content_reports(reporter_id, reply_id) where reply_id is not null and status = 'pending';
create index if not exists content_reports_admin_queue_idx on public.content_reports(status, created_at desc);

create table if not exists public.community_rate_events (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references public.profiles(id) on delete cascade,
  action_key text not null,
  created_at timestamptz not null default now()
);
create index if not exists community_rate_events_actor_action_idx
on public.community_rate_events(actor_id, action_key, created_at desc);

alter table public.content_reports enable row level security;
alter table public.community_rate_events enable row level security;

create policy content_reports_insert_own on public.content_reports for insert to authenticated
with check (reporter_id = auth.uid() and status = 'pending' and resolved_by is null and resolved_at is null);
create policy content_reports_read_own_or_admin on public.content_reports for select to authenticated
using (reporter_id = auth.uid() or public.is_platform_admin());
create policy content_reports_admin_update on public.content_reports for update to authenticated
using (public.is_platform_admin()) with check (public.is_platform_admin());
create policy community_rate_events_admin_read on public.community_rate_events for select to authenticated
using (public.is_platform_admin());

create or replace function public.enforce_community_rate_limit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  active_actor uuid := auth.uid();
  action_name text;
  allowed_count integer;
  window_interval interval;
  recent_count integer;
begin
  if active_actor is null or auth.role() = 'service_role' then return new; end if;
  action_name := case tg_table_name
    when 'content_entries' then 'content_entry_create'
    when 'content_replies' then 'content_reply_create'
    when 'content_entry_reactions' then 'content_entry_reaction'
    when 'content_reply_reactions' then 'content_reply_reaction'
    else 'community_write'
  end;
  allowed_count := case action_name
    when 'content_entry_create' then 10
    when 'content_reply_create' then 30
    else 120
  end;
  window_interval := interval '1 hour';
  select count(*)::integer into recent_count
  from public.community_rate_events event
  where event.actor_id = active_actor and event.action_key = action_name
    and event.created_at > now() - window_interval;
  if recent_count >= allowed_count then
    raise exception 'Community rate limit reached. Please try again later.' using errcode = 'P0001';
  end if;
  insert into public.community_rate_events(actor_id, action_key) values(active_actor, action_name);
  return new;
end;
$$;

drop trigger if exists content_entries_rate_limit on public.content_entries;
create trigger content_entries_rate_limit before insert on public.content_entries
for each row execute function public.enforce_community_rate_limit();
drop trigger if exists content_replies_rate_limit on public.content_replies;
create trigger content_replies_rate_limit before insert on public.content_replies
for each row execute function public.enforce_community_rate_limit();
drop trigger if exists content_entry_reactions_rate_limit on public.content_entry_reactions;
create trigger content_entry_reactions_rate_limit before insert on public.content_entry_reactions
for each row execute function public.enforce_community_rate_limit();
drop trigger if exists content_reply_reactions_rate_limit on public.content_reply_reactions;
create trigger content_reply_reactions_rate_limit before insert on public.content_reply_reactions
for each row execute function public.enforce_community_rate_limit();

create or replace function public.protect_content_moderation_state()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.moderation_status is distinct from old.moderation_status and not public.is_platform_admin() then
    raise exception 'Moderation state is administrator-managed.' using errcode = '42501';
  end if;
  return new;
end;
$$;

drop trigger if exists protect_content_entry_moderation on public.content_entries;
create trigger protect_content_entry_moderation before update of moderation_status on public.content_entries
for each row execute function public.protect_content_moderation_state();
drop trigger if exists protect_content_reply_moderation on public.content_replies;
create trigger protect_content_reply_moderation before update of moderation_status on public.content_replies
for each row execute function public.protect_content_moderation_state();

drop policy if exists content_entries_read on public.content_entries;
create policy content_entries_read on public.content_entries for select
using (
  public.is_platform_admin()
  or (publication_status = 'published' and moderation_status = 'visible')
  or author_id = auth.uid()
  or (item_id is not null and public.can_manage_item(item_id))
);
drop policy if exists content_replies_read on public.content_replies;
create policy content_replies_read on public.content_replies for select
using (
  public.is_platform_admin()
  or (public.can_read_content(entry_id) and (moderation_status = 'visible' or author_id = auth.uid()))
);

create or replace function public.report_content(
  target_entry_id uuid default null, target_reply_id uuid default null,
  report_reason text default 'other', report_details text default null
) returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare report_id uuid;
begin
  if auth.uid() is null then raise exception 'authentication required' using errcode = '42501'; end if;
  if (target_entry_id is null)::integer + (target_reply_id is null)::integer <> 1 then
    raise exception 'Choose exactly one report target.' using errcode = '22023';
  end if;
  if report_reason not in ('spam', 'harassment', 'hate', 'sexual', 'violence', 'misinformation', 'other') then
    raise exception 'Invalid report reason.' using errcode = '22023';
  end if;
  if target_entry_id is not null and not exists(select 1 from public.content_entries where id = target_entry_id) then
    raise exception 'Content not found.' using errcode = 'P0002';
  end if;
  if target_reply_id is not null and not exists(select 1 from public.content_replies where id = target_reply_id) then
    raise exception 'Reply not found.' using errcode = 'P0002';
  end if;
  insert into public.content_reports(reporter_id, entry_id, reply_id, reason, details)
  values(auth.uid(), target_entry_id, target_reply_id, report_reason, nullif(btrim(report_details), ''))
  on conflict do nothing returning id into report_id;
  if report_id is null then
    select id into report_id from public.content_reports
    where reporter_id = auth.uid() and status = 'pending'
      and ((target_entry_id is not null and entry_id = target_entry_id) or (target_reply_id is not null and reply_id = target_reply_id));
  end if;
  return report_id;
end;
$$;

create or replace function public.resolve_content_report(
  target_report_id uuid, target_status text, target_moderation_status text default null,
  target_resolution_note text default null
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare report_row public.content_reports;
begin
  if not public.is_platform_admin() then raise exception 'Administrator access required.' using errcode = '42501'; end if;
  if target_status not in ('reviewed', 'dismissed', 'actioned') then raise exception 'Invalid report status.' using errcode = '22023'; end if;
  if target_moderation_status is not null and target_moderation_status not in ('visible', 'hidden', 'removed') then
    raise exception 'Invalid moderation status.' using errcode = '22023';
  end if;
  select * into report_row from public.content_reports where id = target_report_id for update;
  if report_row.id is null then raise exception 'Report not found.' using errcode = 'P0002'; end if;
  if target_moderation_status is not null then
    if report_row.entry_id is not null then update public.content_entries set moderation_status = target_moderation_status where id = report_row.entry_id;
    else update public.content_replies set moderation_status = target_moderation_status where id = report_row.reply_id;
    end if;
  end if;
  update public.content_reports set status = target_status, resolved_by = auth.uid(),
    resolution_note = nullif(btrim(target_resolution_note), ''), resolved_at = now()
  where id = target_report_id;
end;
$$;

revoke all on function public.report_content(uuid, uuid, text, text) from public, anon;
revoke all on function public.resolve_content_report(uuid, text, text, text) from public, anon;
revoke execute on function public.enforce_community_rate_limit() from public, anon, authenticated;
revoke execute on function public.protect_content_moderation_state() from public, anon, authenticated;
grant execute on function public.report_content(uuid, uuid, text, text) to authenticated, service_role;
grant execute on function public.resolve_content_report(uuid, text, text, text) to authenticated, service_role;
grant select, insert on public.content_reports to authenticated;
grant select on public.community_rate_events to authenticated;
revoke all on public.content_reports, public.community_rate_events from anon;
